# Site settings
title: "Indolamine blog"
description: > 
  Software, productivity, clojure

author: Gabor Veres
email: hello@indolamine.io
twitter_username: indolamine_io
github_username: indolamine

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://indolamine.io" # the base hostname & protocol for your site

google_analytics_id: UA-1111111111-1
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]

